name: Documentation

on:
  push:
    paths:
      - "**.md"
      - "**.png"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: justalemon/MarkdownMaterial@master
        with:
          cname: "lambentlight.justalemon.ml"
      - uses: justalemon/DeployToBranch@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
